---
- name: Insall git
  package:
    pkg=git
    state=latest
    update_cache=yes

- name: Bower install package
  bower: path={{ development_path }}

- name: Install dependencies
  bower:
    name: "{{ item.name|default(omit) }}"
    offline: "{{ item.offline|default(omit) }}"
    path: "{{ item.path|default(omit) }}"
    producion: "{{ item.production|default(omit) }}"
    relative_execpath: "{{ item.relative_execpath|default(omit) }}"
    state: "{{ item.state|default(omit) }}"
    version: "{{ item.version|default(omit) }}"
  with_items: "{{ bower_packages }}"
  when: "{{ bower_packages }}"
